version: "2"
run:
  timeout: 2m
  tests: true
  skip-dirs:
    - tmp
    - database
    - s3
  skip-files:
    - ".*_templ\\.go$"
linters:
  default: all
  enable:
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

linters-settings:
  errcheck:
    check-blank: true
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*os.File).Close

  gocyclo:
    min-complexity: 15

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
