profile: tmp/cover.out
threshold:
#TODO adjust thresholds upwards when tests are improved
  file: 0 # 70
  package: 0 # 80
  total: 2 #95
exclude:
  paths:
    - \*_templ\.go$    # excludes all templ template files

# (optional; default false)
# When true, requires all coverage-ignore annotations to include explanatory comments
force-annotation-comment: false
