profile: tmp/cover.out
#TODO adjust thresholds upwards when tests are improved
threshold:
  file: 0 # 70
  package: 0 # 80
  total: 60 #95
exclude:
  paths:
    - '.*_templ\.go$'    # exclude all templ template files

# (optional; default false)
# When true, requires all coverage-ignore annotations to include explanatory comments
force-annotation-comment: false
