services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - ./internal/templates:/app/internal/templates
      - ./static:/app/static